# Generated by Django 3.2.4 on 2021-06-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_modelocliente_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelocliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='modelocliente',
            name='dni',
            field=models.IntegerField(default=0, help_text='Escribir número sin puntos', max_length=15, unique=True),
        ),
    ]
