# Generated by Django 3.2.4 on 2021-06-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210616_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modeloCliente',
            new_name='ciente',
        ),
        migrations.AlterModelOptions(
            name='ciente',
            options={'ordering': ['apellido']},
        ),
    ]
