# Generated by Django 3.2.4 on 2021-06-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20210616_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ciente',
            new_name='clientes',
        ),
    ]
