# Generated by Django 3.2.4 on 2021-06-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_rename_ciente_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.IntegerField(default=0, max_length=15, unique=True),
        ),
    ]
