# Generated by Django 3.2.4 on 2021-06-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_clientes_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.IntegerField(max_length=25, unique=True),
        ),
    ]
