# Generated by Django 3.2.4 on 2021-06-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
